module: CaffeineKit
author: aaplmath

swift_version: 5.1.2
min_acl: public

output: docs
clean: true

docset_icon: logo.png
author_url: https://aaplmath.github.io
github_url: https://github.com/aaplmath/CaffeineKit
root_url: https://aaplmath.github.io/CaffeineKit/

copyright: 'Copyright &copy; 2020 aaplmath. CaffeineKit is made available under the [MIT License](https://github.com/aaplmath/CaffeineKit/blob/master/LICENSE).'
theme: apple

github_file_prefix: https://github.com/aaplmath/CaffeineKit/tree/v0.3.1
module_version: 0.3.1
